-- Generated by drizzle-kit. KEEP THIS IDEMPOTENT: migrations run on every API
-- container start (see ../Dockerfile), so a statement that fails on re-run
-- crash-loops the API — which is what took RentVault down on 2026-07-24.
-- drizzle-kit already emits CREATE TABLE/INDEX IF NOT EXISTS and wraps
-- ALTER TABLE ... ADD CONSTRAINT in a DO $$ ... EXCEPTION WHEN duplicate_object
-- guard; if you hand-edit or add statements here, match that pattern
-- (ADD COLUMN IF NOT EXISTS, etc).
CREATE TABLE IF NOT EXISTS "ad_accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" text DEFAULT 'google_ads' NOT NULL,
	"customer_id" text NOT NULL,
	"descriptive_name" text,
	"currency_code" text,
	"time_zone" text,
	"login_customer_id" text,
	"is_test_account" text DEFAULT 'unknown' NOT NULL,
	"refresh_token_ciphertext" text NOT NULL,
	"scope" text,
	"status" text DEFAULT 'active' NOT NULL,
	"last_refreshed_at" timestamp with time zone,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ad_accounts_provider_check" CHECK ("ad_accounts"."provider" in ('google_ads')),
	CONSTRAINT "ad_accounts_status_check" CHECK ("ad_accounts"."status" in ('active','revoked')),
	CONSTRAINT "ad_accounts_test_check" CHECK ("ad_accounts"."is_test_account" in ('yes','no','unknown')),
	CONSTRAINT "ad_accounts_customer_id_check" CHECK ("ad_accounts"."customer_id" ~ '^[0-9]{5,20}$')
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"kind" text DEFAULT 'photo' NOT NULL,
	"r2_key" text NOT NULL,
	"content_type" text NOT NULL,
	"size_bytes" integer,
	"original_filename" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "assets_r2_key_unique" UNIQUE("r2_key"),
	CONSTRAINT "assets_kind_check" CHECK ("assets"."kind" in ('photo','logo'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"ad_account_id" uuid,
	"name" text NOT NULL,
	"business_name" text NOT NULL,
	"business_category" text NOT NULL,
	"call_to_action" text DEFAULT 'Call now' NOT NULL,
	"landing_url" text NOT NULL,
	"offer_details" text,
	"target_zip_codes" text[] NOT NULL,
	"radius_miles" integer DEFAULT 10 NOT NULL,
	"daily_budget_cents" integer NOT NULL,
	"currency_code" text DEFAULT 'USD' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"google_campaign_resource_name" text,
	"google_budget_resource_name" text,
	"launch_error" text,
	"launched_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "campaigns_status_check" CHECK ("campaigns"."status" in ('draft','rendering','ready','live','paused','failed')),
	CONSTRAINT "campaigns_budget_check" CHECK ("campaigns"."daily_budget_cents" > 0),
	CONSTRAINT "campaigns_radius_check" CHECK ("campaigns"."radius_miles" between 1 and 50),
	CONSTRAINT "campaigns_zips_check" CHECK (array_length("campaigns"."target_zip_codes", 1) between 1 and 50)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "creatives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"campaign_id" uuid NOT NULL,
	"aspect_ratio" text NOT NULL,
	"script" jsonb,
	"script_source" text,
	"source_asset_keys" text[] DEFAULT '{}'::text[] NOT NULL,
	"render_status" text DEFAULT 'queued' NOT NULL,
	"render_error" text,
	"video_key" text,
	"thumbnail_key" text,
	"duration_seconds" integer,
	"size_bytes" integer,
	"youtube_video_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"rendered_at" timestamp with time zone,
	CONSTRAINT "creatives_aspect_check" CHECK ("creatives"."aspect_ratio" in ('16:9','9:16')),
	CONSTRAINT "creatives_render_status_check" CHECK ("creatives"."render_status" in ('queued','rendering','ready','failed'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "render_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"creative_id" uuid NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"claimed_by" text,
	"claimed_at" timestamp with time zone,
	"run_after" timestamp with time zone DEFAULT now() NOT NULL,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "render_jobs_status_check" CHECK ("render_jobs"."status" in ('queued','running','done','failed'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"refresh_token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"display_name" text,
	"business_name" text,
	"business_category" text,
	"phone" text,
	"role" text DEFAULT 'advertiser' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('advertiser','admin'))
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ad_accounts" ADD CONSTRAINT "ad_accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "assets" ADD CONSTRAINT "assets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_ad_account_id_ad_accounts_id_fk" FOREIGN KEY ("ad_account_id") REFERENCES "public"."ad_accounts"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "creatives" ADD CONSTRAINT "creatives_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "render_jobs" ADD CONSTRAINT "render_jobs_creative_id_creatives_id_fk" FOREIGN KEY ("creative_id") REFERENCES "public"."creatives"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ad_accounts_user" ON "ad_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_ad_accounts_user_provider_customer" ON "ad_accounts" USING btree ("user_id","provider","customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_assets_user" ON "assets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_campaigns_user" ON "campaigns" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_campaigns_status" ON "campaigns" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_creatives_campaign" ON "creatives" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_render_jobs_claim" ON "render_jobs" USING btree ("status","run_after");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_render_jobs_creative_open" ON "render_jobs" USING btree ("creative_id") WHERE status in ('queued','running');--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sessions_user" ON "sessions" USING btree ("user_id");