-- Generated by drizzle-kit, then HAND-EDITED FOR IDEMPOTENCY.
-- drizzle-kit emits bare ADD COLUMN / ADD CONSTRAINT, which are NOT idempotent.
-- Migrations run on every API container start (see ../Dockerfile), so a
-- statement that fails on re-run crash-loops production — that is what took
-- RentVault down on 2026-07-24. ADD COLUMN carries IF NOT EXISTS and every
-- ADD CONSTRAINT is wrapped in a DO $$ ... WHEN duplicate_object guard.
-- Verified by replaying this file against an already-migrated database:
-- only "already exists, skipping" notices, exit 0.
-- Match that pattern if you hand-edit or add statements here.
CREATE TABLE IF NOT EXISTS "ledger_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"wallet_id" uuid NOT NULL,
	"type" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"currency_code" text NOT NULL,
	"description" text,
	"campaign_id" uuid,
	"external_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_type_check" CHECK ("ledger_entries"."type" in ('topup','spend','fee','refund','adjustment')),
	CONSTRAINT "ledger_currency_check" CHECK ("ledger_entries"."currency_code" in ('INR','USD')),
	CONSTRAINT "ledger_sign_check" CHECK (("ledger_entries"."type" = 'topup' and "ledger_entries"."amount_minor" > 0)
          or ("ledger_entries"."type" in ('spend','fee','refund') and "ledger_entries"."amount_minor" < 0)
          or ("ledger_entries"."type" = 'adjustment' and "ledger_entries"."amount_minor" <> 0))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"provider_ref" text,
	"amount_minor" integer NOT NULL,
	"currency_code" text NOT NULL,
	"purpose" text NOT NULL,
	"status" text DEFAULT 'created' NOT NULL,
	"provider_payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payments_provider_check" CHECK ("payments"."provider" in ('razorpay','stripe','manual')),
	CONSTRAINT "payments_currency_check" CHECK ("payments"."currency_code" in ('INR','USD')),
	CONSTRAINT "payments_purpose_check" CHECK ("payments"."purpose" in ('topup','creation_fee','subscription')),
	CONSTRAINT "payments_status_check" CHECK ("payments"."status" in ('created','paid','failed','cancelled')),
	CONSTRAINT "payments_amount_check" CHECK ("payments"."amount_minor" > 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "wallets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"balance_minor" integer DEFAULT 0 NOT NULL,
	"currency_code" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wallets_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "wallets_currency_check" CHECK ("wallets"."currency_code" in ('INR','USD')),
	CONSTRAINT "wallets_balance_non_negative" CHECK ("wallets"."balance_minor" >= 0)
);
--> statement-breakpoint
ALTER TABLE "ad_accounts" ALTER COLUMN "refresh_token_ciphertext" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ad_accounts" ADD COLUMN IF NOT EXISTS "is_managed" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "ad_accounts" ADD COLUMN IF NOT EXISTS "manager_customer_id" text;--> statement-breakpoint
ALTER TABLE "ad_accounts" ADD COLUMN IF NOT EXISTS "provision_status" text;--> statement-breakpoint
ALTER TABLE "ad_accounts" ADD COLUMN IF NOT EXISTS "provision_error" text;--> statement-breakpoint
ALTER TABLE "ad_accounts" ADD COLUMN IF NOT EXISTS "provisioned_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "google_customer_id" text;--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "spend_minor_to_date" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "last_spend_synced_date" text;--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "paused_for_funds_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "creatives" ADD COLUMN IF NOT EXISTS "motion_clip_keys" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "creatives" ADD COLUMN IF NOT EXISTS "motion_source" text DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "creatives" ADD COLUMN IF NOT EXISTS "voiceover_key" text;--> statement-breakpoint
ALTER TABLE "creatives" ADD COLUMN IF NOT EXISTS "voice_source" text DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "country_code" text DEFAULT 'US' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "currency_code" text DEFAULT 'USD' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "margin_mode" text DEFAULT 'standard' NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_wallet_id_wallets_id_fk" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallets"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "payments" ADD CONSTRAINT "payments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "wallets" ADD CONSTRAINT "wallets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ledger_wallet" ON "ledger_entries" USING btree ("wallet_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_ledger_wallet_ref" ON "ledger_entries" USING btree ("wallet_id","external_ref") WHERE external_ref is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_payments_user" ON "payments" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_payments_provider_ref" ON "payments" USING btree ("provider","provider_ref") WHERE provider_ref is not null;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ad_accounts" ADD CONSTRAINT "ad_accounts_provision_status_check" CHECK ("ad_accounts"."provision_status" is null or "ad_accounts"."provision_status" in ('pending','active','failed'));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ad_accounts" ADD CONSTRAINT "ad_accounts_managed_token_check" CHECK (("ad_accounts"."is_managed" = true and "ad_accounts"."refresh_token_ciphertext" is null)
          or ("ad_accounts"."is_managed" = false and "ad_accounts"."refresh_token_ciphertext" is not null));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "creatives" ADD CONSTRAINT "creatives_motion_source_check" CHECK ("creatives"."motion_source" in ('none','kling','luma'));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "creatives" ADD CONSTRAINT "creatives_voice_source_check" CHECK ("creatives"."voice_source" in ('none','edge-tts','elevenlabs'));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "users" ADD CONSTRAINT "users_currency_check" CHECK ("users"."currency_code" in ('INR','USD'));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "users" ADD CONSTRAINT "users_margin_mode_check" CHECK ("users"."margin_mode" in ('standard','at_cost'));
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
